create table if not exists public.company_demo_metrics (
  company_id uuid primary key references public.companies(id) on delete cascade,
  employee_count integer not null default 0,
  training_total integer not null default 0,
  training_completed integer not null default 0,
  inspection_total integer not null default 0,
  inspection_completed integer not null default 0,
  open_dof integer not null default 0,
  accident_count integer not null default 0,
  near_miss_count integer not null default 0,
  health_total integer not null default 0,
  health_current integer not null default 0,
  document_total integer not null default 0,
  document_current integer not null default 0,
  overall_score integer not null default 0,
  risk_score integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.company_demo_activity (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  activity_type text not null,
  title text not null,
  description text,
  status text not null default 'INFO',
  occurred_at timestamptz not null default now()
);

create index if not exists idx_company_demo_activity_company_id
  on public.company_demo_activity(company_id);

alter table public.company_demo_metrics enable row level security;
alter table public.company_demo_activity enable row level security;

drop policy if exists "company_demo_metrics_admin_read" on public.company_demo_metrics;
create policy "company_demo_metrics_admin_read"
on public.company_demo_metrics
for select
using (true);

drop policy if exists "company_demo_activity_admin_read" on public.company_demo_activity;
create policy "company_demo_activity_admin_read"
on public.company_demo_activity
for select
using (true);
