"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useParams, useRouter } from "next/navigation";

type Firm = { id:string; firm_name:string; sgk_no?:string|null; tax_no?:string|null; nace_code?:string|null; sector?:string|null; danger_class?:string|null; employee_count?:number|null; address?:string|null; phone?:string|null; email?:string|null; authorized_person?:string|null; setup_score?:number|null; };
function value(v:unknown){return String(v??"").trim()}

export default function DoraExpertPage(){
 const router=useRouter(); const params=useParams(); const firmId=value(params.firmId);
 const [firm,setFirm]=useState<Firm|null>(null); const [employeeCount,setEmployeeCount]=useState(0); const [riskCount,setRiskCount]=useState(0); const [documentCount,setDocumentCount]=useState(0); const [trainingCount,setTrainingCount]=useState(0); const [expert,setExpert]=useState<any>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 const load=useCallback(async()=>{ if(!firmId)return; try{setLoading(true);setError(""); const [f,e,r,d,t,x]=await Promise.all([
  fetch(`/api/dora/firms?id=${encodeURIComponent(firmId)}`,{cache:"no-store"}), fetch(`/api/dora/employees?firmId=${encodeURIComponent(firmId)}`,{cache:"no-store"}), fetch(`/api/dora/risks?firmId=${encodeURIComponent(firmId)}`,{cache:"no-store"}), fetch(`/api/dora/documents?firmId=${encodeURIComponent(firmId)}`,{cache:"no-store"}), fetch(`/api/dora/module-state?firmId=${encodeURIComponent(firmId)}&moduleKey=TRAINING`,{cache:"no-store"}), fetch(`/api/dora/module-state?firmId=${encodeURIComponent(firmId)}&moduleKey=EXPERT`,{cache:"no-store"})]);
  const fj=await f.json(), ej=await e.json(), rj=await r.json(), dj=await d.json(), tj=await t.json(), xj=await x.json(); if(!f.ok||fj.success===false)throw new Error(fj.error||"Firma alınamadı."); setFirm(fj.firm??null); setEmployeeCount(Array.isArray(ej.employees)?ej.employees.length:0); setRiskCount(Array.isArray(rj.risks)?rj.risks.length:0); setDocumentCount(Array.isArray(dj.documents)?dj.documents.length:0); setTrainingCount(Array.isArray(tj.payload?.items)?tj.payload.items.length:Number(tj.payload?.count??0)||0); setExpert(xj.payload??{});
 }catch(e){setError(e instanceof Error?e.message:"DORA Expert yüklenemedi.")}finally{setLoading(false)} },[firmId]); useEffect(()=>{void load()},[load]);
 const checks=useMemo(()=>{if(!firm)return[];return[
  ["Firma ünvanı",!!value(firm.firm_name)],["SGK sicil",!!value(firm.sgk_no)],["Vergi/kimlik",!!value(firm.tax_no)],["NACE",!!value(firm.nace_code)],["Sektör",!!value(firm.sector)],["Tehlike sınıfı",!!value(firm.danger_class)],["İletişim",!!value(firm.address)&&!!value(firm.phone)&&!!value(firm.email)],["Yetkili",!!value(firm.authorized_person)],["Çalışan havuzu",employeeCount>0],["Risk değerlendirmesi",riskCount>0],["Eğitim planı",trainingCount>0],["Doküman üretimi",documentCount>0]
 ] as [string,boolean][]},[firm,employeeCount,riskCount,trainingCount,documentCount]);
 const completed=checks.filter(x=>x[1]).length; const score=checks.length?Math.round(completed/checks.length*100):0; const missing=checks.filter(x=>!x[1]).map(x=>x[0]);
 const tasks=useMemo(()=>{const out:string[]=[];if(employeeCount===0)out.push("Çalışan listesini oluşturun ve görevlendirmeleri tamamlayın.");if(riskCount===0)out.push("Fine Kinney risk değerlendirmesi kayıtlarını oluşturun.");if(trainingCount===0)out.push("Yıllık eğitim planını ve eğitim oturumlarını oluşturun.");if(documentCount===0)out.push("Kurumsal DORA doküman paketini oluşturun.");if(!firm?.authorized_person)out.push("İşveren / işveren vekili ve kurumsal yetkili bilgisini tamamlayın.");if(!out.length)out.push("Temel DORA kurulumu tamamlandı; açık aksiyon ve periyodik güncellemeleri izleyin.");return out},[employeeCount,riskCount,trainingCount,documentCount,firm]);
 async function saveExpert(robotStarted:boolean){const payload={setupScore:score,completedChecks:completed,totalChecks:checks.length,missingFields:missing,tasks,robotStarted,generatedDocumentCount:robotStarted?documentCount:0,updatedAtMillis:Date.now()}; const res=await fetch("/api/dora/module-state",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({firmId,moduleKey:"EXPERT",payload})}); const j=await res.json();if(!res.ok||j.success===false)throw new Error(j.error||"Expert durumu kaydedilemedi.");setExpert(payload)}
 if(loading)return <main className="page">DORA Expert yükleniyor...</main>;
 return <main className="page"><div className="topbar"><button className="outline" onClick={()=>router.push(`/admin/dora/${firmId}`)}>← Firma Merkezine Dön</button><button className="outline" onClick={()=>void load()}>Yenile</button></div>
 <section className="hero"><div><div className="eyebrow">DORA • EXPERT ENGINE</div><h1>DORA Durum Analizi ve Robot</h1><p>{firm?.firm_name||"Firma"} için kurulum durumunu, eksiklikleri, öncelikli iş planını ve robot üretim kuyruğunu Web/App ortak verileriyle izleyin.</p></div><div className="score"><strong>%{score}</strong><span>{completed}/{checks.length} tamam</span></div></section>{error&&<div className="error">{error}</div>}
 <section className="kpis"><Kpi t="Kurulum Skoru" v={`%${score}`} d="Ortak DORA durumu"/><Kpi t="Çalışan" v={employeeCount} d="DORA çalışanları"/><Kpi t="Risk" v={riskCount} d="Fine Kinney kayıtları"/><Kpi t="Eğitim" v={trainingCount} d="DORA eğitimleri"/></section>
 <section className="grid"><article className="panel"><span>DORA EXPERT ÖZETİ</span><h2>Durum ve Eksikler</h2><div className="checks">{checks.map(([n,ok])=><div className={ok?"check ok":"check missing"} key={n}><b>{ok?"✓":"!"}</b><span>{n}</span><strong>{ok?"Tamam":"Eksik"}</strong></div>)}</div></article>
 <article className="panel"><span>ÖNCELİKLİ İŞ PLANI</span><h2>DORA'nın Önerdiği Sıra</h2><ol>{tasks.map((t,i)=><li key={i}>{t}</li>)}</ol><div className="robotBox"><strong>Robot Durumu</strong><p>{expert.robotStarted?"Robotik üretim kuyruğu başlatıldı.":"Robotik üretim henüz başlatılmadı."}</p><button className="primary" onClick={()=>void saveExpert(true)}>Robot İş Kuyruğunu Başlat</button></div></article></section>
 <section className="panel wide"><span>DORA ROBOT İŞ KUYRUĞU</span><h2>Kurumsal Üretim ve Takip</h2>{tasks.map((t,i)=><article className="queue" key={i}><div className="queueNo">{i+1}</div><div><strong>{t}</strong><p>{expert.robotStarted?"Kuyrukta / kontrol bekliyor":"Analiz önerisi"}</p></div></article>)}</section><style jsx>{styles}</style></main>
}
function Kpi({t,v,d}:{t:string;v:string|number;d:string}){return <article className="kpi"><span>{t}</span><strong>{v}</strong><small>{d}</small></article>}
const styles=`:global(*){box-sizing:border-box}.page{min-height:100vh;padding:24px;color:#172033;background:linear-gradient(180deg,#f7f8fb,#fff 430px)}button{font:inherit;cursor:pointer}.topbar,.hero,.kpis,.grid,.wide{max-width:1450px;margin-left:auto;margin-right:auto}.topbar{display:flex;justify-content:space-between;margin-bottom:14px}.outline,.primary{padding:10px 14px;border-radius:12px;font-weight:850}.outline{border:1px solid #d0d5dd;background:#fff;color:#344054}.primary{border:0;background:#7a2633;color:#fff}.hero{padding:32px;border-radius:28px;display:flex;justify-content:space-between;gap:24px;align-items:center;color:#fff;background:linear-gradient(120deg,#50141f,#7a2633 48%,#d0602c)}.eyebrow,.panel>span{font-size:11px;font-weight:900;letter-spacing:.13em}.hero h1{margin:8px 0;font-size:clamp(32px,5vw,52px)}.hero p{max-width:760px;line-height:1.6;color:rgba(255,255,255,.86)}.score{min-width:170px;padding:24px;border-radius:22px;text-align:center;background:rgba(255,255,255,.13);border:1px solid rgba(255,255,255,.2)}.score strong{display:block;font-size:42px}.score span{font-weight:800}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:18px}.kpi,.panel{background:#fff;border:1px solid #e4e7ec;border-radius:20px}.kpi{padding:18px}.kpi span,.kpi small{display:block;color:#667085}.kpi strong{display:block;font-size:30px;margin:8px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:18px}.panel{padding:22px}.panel>span{color:#8c3543}.panel h2{margin:7px 0 16px}.checks{display:grid;gap:8px}.check{display:grid;grid-template-columns:28px 1fr auto;gap:10px;padding:11px;border-radius:12px}.check.ok{background:#f0fdf4;color:#067647}.check.missing{background:#fff7ed;color:#b54708}.panel ol{padding-left:22px;color:#475467;line-height:1.8}.robotBox{margin-top:18px;padding:16px;border-radius:16px;background:#fff6f2}.robotBox p{color:#667085}.wide{margin-top:18px}.queue{display:flex;gap:12px;align-items:center;padding:14px;border-top:1px solid #eaecf0}.queueNo{width:36px;height:36px;display:grid;place-items:center;border-radius:50%;background:#fff0f2;color:#8c3543;font-weight:900}.queue p{margin:4px 0 0;color:#667085}.error{max-width:1450px;margin:16px auto;padding:15px;background:#fff2f2;color:#b42318;border-radius:14px}@media(max-width:900px){.hero{flex-direction:column;align-items:flex-start}.kpis,.grid{grid-template-columns:1fr}}`;
