"use client";
import {useState,type CSSProperties} from "react";
import PrescriptionHistory from "./PrescriptionHistory";

type Item={medicineName:string;activeIngredient:string;dosage:string;usageType:string;duration:string;morning:boolean;noon:boolean;evening:boolean;night:boolean;beforeMeal:boolean;afterMeal:boolean;notes:string};
type Props={employee:{id:string;full_name:string;company_id?:string;company_name?:string;job_title?:string}};
const blank:Item={medicineName:"",activeIngredient:"",dosage:"",usageType:"",duration:"",morning:false,noon:false,evening:false,night:false,beforeMeal:false,afterMeal:false,notes:""};
export default function PrescriptionWorkspace({employee}:Props){
 const [id,setId]=useState(""),[diagnosisCode,setDiagnosisCode]=useState(""),[diagnosisName,setDiagnosisName]=useState(""),[notes,setNotes]=useState(""),[doctorTc,setDoctorTc]=useState(""),[diploma,setDiploma]=useState(""),[medulaStatus,setMedulaStatus]=useState("NOT_SENT"),[eNo,setENo]=useState(""),[tracking,setTracking]=useState(""),[medulaResponse,setMedulaResponse]=useState(""),[items,setItems]=useState<Item[]>([{...blank}]),[saving,setSaving]=useState(false),[msg,setMsg]=useState(""),[refresh,setRefresh]=useState(0),[icd,setIcd]=useState<any[]>([]),[drug,setDrug]=useState<Record<number,any[]>>({});
 const upd=<K extends keyof Item>(i:number,k:K,v:Item[K])=>setItems(p=>p.map((x,n)=>n===i?{...x,[k]:v}:x));
 async function searchIcd(q:string){setDiagnosisCode(q);if(q.length<2){setIcd([]);return}try{const r=await fetch(`/api/admin/icd10/search?q=${encodeURIComponent(q)}`);const j=await r.json();setIcd(j.items||[])}catch{setIcd([])}}
 async function searchDrug(i:number,q:string){upd(i,"medicineName",q);if(q.length<2){setDrug(p=>({...p,[i]:[]}));return}try{const r=await fetch(`/api/admin/drugs/search?q=${encodeURIComponent(q)}`);const j=await r.json();setDrug(p=>({...p,[i]:j.items||[]}))}catch{}}
 function selectDrug(i:number,d:any){upd(i,"medicineName",d.drug_name||"");upd(i,"activeIngredient",d.active_ingredient||"");upd(i,"dosage",d.strength||"");upd(i,"usageType",d.dosage_form||"");setDrug(p=>({...p,[i]:[]}))}
 async function save(status="draft"){try{setSaving(true);setMsg("");const r=await fetch(id?`/api/admin/health-prescriptions/${id}`:"/api/admin/health-prescriptions",{method:id?"PUT":"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({employeeId:employee.id,companyId:employee.company_id,diagnosisCode,diagnosisName,doctorIdentityNumber:doctorTc,doctorDiplomaNo:diploma,notes,status,items})});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success)throw new Error(j.error||"Reçete kaydedilemedi.");const p=j.prescription;setId(p.id);setMedulaStatus(p.medula_status||"NOT_SENT");setENo(p.e_prescription_no||"");setTracking(p.medula_tracking_no||"");setMedulaResponse(p.medula_response||"");setMsg("Reçete kaydedildi.");setRefresh(x=>x+1)}catch(e:any){setMsg(e.message||"Reçete kaydedilemedi.")}finally{setSaving(false)}}
 async function ready(){if(!id){setMsg("Önce reçeteyi kaydedin.");return}try{const r=await fetch(`/api/admin/health-prescriptions/${id}/medula-status`,{method:"PUT",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({medulaStatus:"READY"})});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||"Durum güncellenemedi.");setMedulaStatus(j.prescription.medula_status);setMsg("Reçete e-Reçete entegrasyonuna hazır olarak işaretlendi.");setRefresh(x=>x+1)}catch(e:any){setMsg(e.message)}}
 async function load(pid:string){const r=await fetch(`/api/admin/health-prescriptions/${pid}`,{cache:"no-store",credentials:"include"});const j=await r.json();if(!r.ok||!j.success){alert(j.error||"Reçete yüklenemedi.");return}const p=j.prescription;setId(p.id);setDiagnosisCode(p.diagnosis_code||"");setDiagnosisName(p.diagnosis_name||"");setDoctorTc(p.doctor_identity_number||"");setDiploma(p.doctor_diploma_no||"");setNotes(p.notes||"");setMedulaStatus(p.medula_status||"NOT_SENT");setENo(p.e_prescription_no||"");setTracking(p.medula_tracking_no||"");setMedulaResponse(p.medula_response||"");setItems((p.health_prescription_items||[]).map((x:any)=>({medicineName:x.medicine_name||"",activeIngredient:x.active_ingredient||"",dosage:x.dosage||"",usageType:x.usage_type||"",duration:x.duration||"",morning:!!x.morning,noon:!!x.noon,evening:!!x.evening,night:!!x.night,beforeMeal:!!x.before_meal,afterMeal:!!x.after_meal,notes:x.notes||""})).concat([]).length?(p.health_prescription_items||[]).map((x:any)=>({medicineName:x.medicine_name||"",activeIngredient:x.active_ingredient||"",dosage:x.dosage||"",usageType:x.usage_type||"",duration:x.duration||"",morning:!!x.morning,noon:!!x.noon,evening:!!x.evening,night:!!x.night,beforeMeal:!!x.before_meal,afterMeal:!!x.after_meal,notes:x.notes||""})):[{...blank}]);window.scrollTo({top:0,behavior:"smooth"})}
 function fresh(){setId("");setDiagnosisCode("");setDiagnosisName("");setDoctorTc("");setDiploma("");setNotes("");setMedulaStatus("NOT_SENT");setENo("");setTracking("");setMedulaResponse("");setItems([{...blank}]);setMsg("")}
 return <div style={{display:"grid",gap:14}}>
  <section style={card}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><div style={eyebrow}>D-SEC SAĞLIK • REÇETE MERKEZİ</div><h2 style={{margin:"5px 0 4px"}}>Reçete / e-Reçete Hazırlık Alanı</h2><div style={muted}>Reçete kaydı, ilaç kalemleri ve e-Reçete hazırlık durumu birlikte yönetilir.</div></div><div style={{display:"flex",gap:7}}><Badge text={id?"Düzenleme":"Yeni reçete"}/><Badge text={medulaLabel(medulaStatus)} tone={medulaStatus==="READY"?"good":medulaStatus==="ERROR"?"bad":"neutral"}/><button style={btn} onClick={fresh}>Yeni</button></div></div></section>
  <section style={{...card,background:"#fffbeb",borderColor:"#fde68a"}}><b style={{color:"#92400e"}}>MEDULA entegrasyon durumu: Hazırlık</b><div style={{...muted,color:"#92400e",marginTop:5}}>Bu ekran resmi MEDULA gönderimi yapmaz. “Hazır” durumu D-SEC içindeki veri hazırlığını ifade eder. SENT/ERROR durumları gerçek dış servis entegrasyonundan gelmelidir.</div></section>
  <section style={card}><h3 style={h3}>Çalışan ve Hekim</h3><div style={grid}><Info label="Çalışan" value={employee.full_name}/><Info label="Firma" value={employee.company_name||"-"}/><Field label="Hekim T.C."><input value={doctorTc} onChange={e=>setDoctorTc(e.target.value.replace(/\D/g,"").slice(0,11))} style={input}/></Field><Field label="Diploma No"><input value={diploma} onChange={e=>setDiploma(e.target.value)} style={input}/></Field></div></section>
  <section style={card}><h3 style={h3}>Tanı</h3><div style={grid}><Field label="ICD-10"><input value={diagnosisCode} onChange={e=>searchIcd(e.target.value)} style={input}/>{icd.length>0&&<div style={drop}>{icd.slice(0,12).map(x=><button key={x.code} type="button" style={option} onClick={()=>{setDiagnosisCode(x.code);setDiagnosisName(x.name);setIcd([])}}><b>{x.code}</b> — {x.name}</button>)}</div>}</Field><Field label="Tanı Adı"><input value={diagnosisName} onChange={e=>setDiagnosisName(e.target.value)} style={input}/></Field></div></section>
  <section style={card}><div style={head}><h3 style={h3}>İlaçlar</h3><button style={btn} onClick={()=>setItems(p=>[...p,{...blank}])}>+ İlaç</button></div><div style={{display:"grid",gap:10}}>{items.map((x,i)=><div key={i} style={medicine}><div style={head}><b>İlaç #{i+1}</b>{items.length>1&&<button style={{...btn,color:"#b91c1c"}} onClick={()=>setItems(p=>p.filter((_,n)=>n!==i))}>Kaldır</button>}</div><div style={grid}><Field label="İlaç adı"><input value={x.medicineName} onChange={e=>searchDrug(i,e.target.value)} style={input}/>{drug[i]?.length>0&&<div style={drop}>{drug[i].slice(0,12).map((d:any)=><button type="button" key={d.id||d.drug_name} style={option} onClick={()=>selectDrug(i,d)}><b>{d.drug_name}</b> — {d.active_ingredient||"-"}</button>)}</div>}</Field><Field label="Etkin madde"><input value={x.activeIngredient} onChange={e=>upd(i,"activeIngredient",e.target.value)} style={input}/></Field><Field label="Doz"><input value={x.dosage} onChange={e=>upd(i,"dosage",e.target.value)} style={input}/></Field><Field label="Kullanım"><input value={x.usageType} onChange={e=>upd(i,"usageType",e.target.value)} style={input}/></Field><Field label="Süre"><input value={x.duration} onChange={e=>upd(i,"duration",e.target.value)} style={input}/></Field></div><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:8}}>{(["morning","noon","evening","night","beforeMeal","afterMeal"] as (keyof Item)[]).map(k=><label key={k} style={{fontSize:11,fontWeight:800}}><input type="checkbox" checked={!!x[k]} onChange={e=>upd(i,k,e.target.checked as any)}/> {({morning:"Sabah",noon:"Öğle",evening:"Akşam",night:"Gece",beforeMeal:"Aç",afterMeal:"Tok"} as any)[k]}</label>)}</div></div>)}</div></section>
  <section style={card}><h3 style={h3}>Not</h3><textarea value={notes} onChange={e=>setNotes(e.target.value)} style={{...input,minHeight:80,resize:"vertical"}}/><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:10,flexWrap:"wrap"}}><button disabled={saving} style={btn} onClick={()=>save("draft")}>{saving?"Kaydediliyor...":"Taslak Kaydet"}</button><button disabled={saving} style={primary} onClick={()=>save("completed")}>Tamamla</button><button disabled={!id||medulaStatus==="READY"} style={readyBtn} onClick={ready}>e-Reçeteye Hazırla</button></div>{msg&&<div style={{marginTop:10,padding:10,borderRadius:10,background:msg.includes("kayded")||msg.includes("hazır")?"#f0fdf4":"#fef2f2",fontSize:11,fontWeight:850}}>{msg}</div>}</section>
  <section style={card}><h3 style={h3}>Entegrasyon Alanları</h3><div style={grid}><Info label="e-Reçete No" value={eNo||"-"}/><Info label="MEDULA Takip No" value={tracking||"-"}/><Info label="MEDULA Durumu" value={medulaLabel(medulaStatus)}/></div>{medulaResponse&&<div style={{...muted,marginTop:10}}>Yanıt: {medulaResponse}</div>}</section>
  <PrescriptionHistory employeeId={employee.id} companyId={employee.company_id} refreshKey={refresh} onEdit={load}/>
 </div>
}
function medulaLabel(v:string){return ({NOT_SENT:"Gönderilmedi",READY:"Hazır",SENT:"Gönderildi",ERROR:"Hata",CANCELLED:"İptal"} as any)[v]||v}
function Badge({text,tone="neutral"}:{text:string;tone?:"neutral"|"good"|"bad"}){return <span style={{padding:"6px 9px",borderRadius:999,fontSize:10,fontWeight:950,background:tone==="good"?"#dcfce7":tone==="bad"?"#fee2e2":"#f2f4f7",color:tone==="good"?"#15803d":tone==="bad"?"#b91c1c":"#475467"}}>{text}</span>}
function Info({label,value}:{label:string;value:string}){return <div><div style={labelStyle}>{label}</div><div style={{fontWeight:900,fontSize:12}}>{value}</div></div>}
function Field({label,children}:{label:string;children:any}){return <label style={{display:"grid",gap:5,position:"relative"}}><span style={labelStyle}>{label}</span>{children}</label>}
const card:CSSProperties={background:"#fff",border:"1px solid #e4e7ec",borderRadius:16,padding:16,boxShadow:"0 7px 20px rgba(16,24,40,.035)"};const eyebrow:CSSProperties={fontSize:9.5,fontWeight:950,letterSpacing:.7,color:"#9f1239"};const muted:CSSProperties={fontSize:11.5,color:"#667085",lineHeight:1.55};const h3:CSSProperties={margin:"0 0 11px",fontSize:15};const grid:CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10};const input:CSSProperties={width:"100%",border:"1px solid #d0d5dd",borderRadius:9,padding:"9px 10px",fontSize:11.5,outline:"none"};const labelStyle:CSSProperties={fontSize:10,color:"#667085",fontWeight:850};const head:CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"center",gap:8,flexWrap:"wrap"};const medicine:CSSProperties={padding:12,border:"1px solid #e4e7ec",borderRadius:12,background:"#f8fafc"};const btn:CSSProperties={border:"1px solid #d0d5dd",background:"#fff",borderRadius:9,padding:"8px 10px",fontSize:10.5,fontWeight:900,cursor:"pointer"};const primary:CSSProperties={...btn,background:"#7f1d1d",borderColor:"#7f1d1d",color:"#fff"};const readyBtn:CSSProperties={...btn,background:"#111827",borderColor:"#111827",color:"#fff"};const drop:CSSProperties={position:"absolute",top:"100%",left:0,right:0,zIndex:20,background:"#fff",border:"1px solid #d0d5dd",borderRadius:9,maxHeight:220,overflow:"auto",boxShadow:"0 10px 25px rgba(0,0,0,.12)"};const option:CSSProperties={display:"block",width:"100%",textAlign:"left",border:0,borderBottom:"1px solid #eee",background:"#fff",padding:9,cursor:"pointer",fontSize:10.5};
