"use client";
import {useState,type CSSProperties} from "react";
type Props={prescriptionId:string;ePrescriptionNo?:string;patientTc?:string;medulaStatus?:string;onChanged?:(x:{status?:string;message?:string})=>void};
export default function MedulaPrescriptionActions({prescriptionId,ePrescriptionNo="",patientTc="",medulaStatus="",onChanged}:Props){
 const[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[remote,setRemote]=useState<any>(null),[list,setList]=useState<any[]>([]);
 async function query(){try{setBusy("query");setMessage("");const r=await fetch(`/api/admin/health-prescriptions/${prescriptionId}/medula-query`,{method:"POST",credentials:"include"});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.resultMessage||j.error||"Sorgu başarısız.");setRemote(j.prescription||null);setMessage("MEDULA kaydı doğrulandı.");onChanged?.({status:"SENT",message:j.resultMessage})}catch(e:any){setMessage(e.message)}finally{setBusy("")}}
 async function listPatient(){try{setBusy("list");setMessage("");const r=await fetch("/api/admin/medula/patient-prescriptions",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({patientTc})});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.resultMessage||j.error||"Liste alınamadı.");setList(j.prescriptions||[]);setMessage(`MEDULA üzerinde ${j.prescriptions?.length||0} reçete bulundu.`)}catch(e:any){setMessage(e.message)}finally{setBusy("")}}
 async function remove(){if(!confirm(`MEDULA üzerindeki ${ePrescriptionNo} numaralı e-Reçete silinecek. Devam edilsin mi?`))return;const typed=prompt("e-Reçete numarasını aynen yazın:");if(typed!==ePrescriptionNo){setMessage("e-Reçete numarası doğrulanamadı.");return}try{setBusy("delete");const r=await fetch(`/api/admin/health-prescriptions/${prescriptionId}/medula-delete`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirm:true})});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.resultMessage||j.error||"Silme başarısız.");setMessage("e-Reçete MEDULA'dan silindi.");onChanged?.({status:"CANCELLED",message:j.resultMessage})}catch(e:any){setMessage(e.message)}finally{setBusy("")}}
 return <section style={card}><div style={head}><div><div style={eyebrow}>MEDULA KAYIT KONTROLÜ</div><h3 style={{margin:"4px 0"}}>Sorgula / Listele / Sil</h3></div><span style={badge}>{medulaStatus||"NOT_SENT"}</span></div><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:12}}><button disabled={!ePrescriptionNo||!!busy} style={primary} onClick={query}>{busy==="query"?"Sorgulanıyor...":"MEDULA'da Sorgula"}</button><button disabled={!patientTc||!!busy} style={secondary} onClick={listPatient}>{busy==="list"?"Alınıyor...":"Hastanın MEDULA Reçeteleri"}</button><button disabled={!ePrescriptionNo||medulaStatus==="CANCELLED"||!!busy} style={danger} onClick={remove}>{busy==="delete"?"Siliniyor...":"MEDULA'dan Sil"}</button></div>{message&&<div style={messageBox}>{message}</div>}{remote&&<details style={details}><summary>MEDULA reçete ayrıntısı</summary><pre style={pre}>{JSON.stringify(remote,null,2)}</pre></details>}{list.length>0&&<details open style={details}><summary>MEDULA hasta reçeteleri ({list.length})</summary><pre style={pre}>{JSON.stringify(list,null,2)}</pre></details>}</section>
}
const card:CSSProperties={background:"#fff",border:"1px solid #e4e7ec",borderRadius:16,padding:16};const head:CSSProperties={display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"};const eyebrow:CSSProperties={fontSize:9.5,fontWeight:950,letterSpacing:.7,color:"#9f1239"};const badge:CSSProperties={padding:"6px 9px",borderRadius:999,fontSize:9.5,fontWeight:950,background:"#f2f4f7"};const base:CSSProperties={borderRadius:9,padding:"9px 12px",fontSize:10.5,fontWeight:950,cursor:"pointer"};const primary:CSSProperties={...base,border:0,background:"#065f46",color:"#fff"};const secondary:CSSProperties={...base,border:"1px solid #d0d5dd",background:"#fff"};const danger:CSSProperties={...base,border:"1px solid #fecaca",background:"#fff",color:"#b91c1c"};const messageBox:CSSProperties={marginTop:10,padding:10,borderRadius:9,background:"#f8fafc",fontSize:11,fontWeight:800};const details:CSSProperties={marginTop:10,border:"1px solid #e4e7ec",borderRadius:10,padding:10};const pre:CSSProperties={whiteSpace:"pre-wrap",overflow:"auto",fontSize:10,background:"#f8fafc",padding:10,borderRadius:8,maxHeight:320};
