"use client";
import {useEffect,useState,type CSSProperties} from "react";
type Row={id:string;diagnosis_code?:string;diagnosis_name?:string;status?:string;medula_status?:string;created_at?:string;health_prescription_items?:any[]};
type Props={employeeId:string;companyId?:string;refreshKey?:number;onEdit?:(id:string)=>void};
export default function PrescriptionHistory({employeeId,companyId,refreshKey=0,onEdit}:Props){
 const [items,setItems]=useState<Row[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;(async()=>{try{setLoading(true);const q=new URLSearchParams({employeeId,limit:"30"});if(companyId)q.set("companyId",companyId);const r=await fetch(`/api/admin/health-prescriptions?${q}`,{cache:"no-store",credentials:"include"});const j=await r.json();if(alive)setItems(r.ok?(j.prescriptions||[]):[])}catch{if(alive)setItems([])}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[employeeId,companyId,refreshKey]);
 async function remove(id:string){if(!confirm("Bu reçeteyi pasife almak istediğinize emin misiniz?"))return;const r=await fetch(`/api/admin/health-prescriptions/${id}`,{method:"DELETE",credentials:"include"});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success){alert(j.error||"Silinemedi.");return}setItems(p=>p.filter(x=>x.id!==id))}
 return <section style={card}><h3 style={{margin:"0 0 12px"}}>Reçete Geçmişi</h3>{loading?<Empty t="Yükleniyor..."/>:items.length===0?<Empty t="Reçete geçmişi bulunamadı."/>:<div style={{display:"grid",gap:8}}>{items.map(x=><div key={x.id} style={row}><div style={{minWidth:0}}><b>{fmt(x.created_at)}</b><div style={{fontSize:11.5,fontWeight:850,marginTop:4}}>{x.diagnosis_code||"-"} {x.diagnosis_name||"Tanı girilmemiş"}</div><div style={{fontSize:10.5,color:"#667085",marginTop:4}}>{x.health_prescription_items?.length||0} ilaç • {x.status||"draft"} • e-Reçete: {x.medula_status||"NOT_SENT"}</div></div><div style={{display:"flex",gap:6,flexWrap:"wrap",justifyContent:"flex-end"}}>{onEdit&&<button style={btn} onClick={()=>onEdit(x.id)}>Düzenle</button>}<a style={pdf} target="_blank" rel="noreferrer" href={`/api/admin/health-prescriptions/${x.id}/pdf`}>PDF</a><button style={{...btn,color:"#b91c1c"}} onClick={()=>remove(x.id)}>Sil</button></div></div>)}</div>}</section>
}
function Empty({t}:{t:string}){return <div style={{padding:18,textAlign:"center",background:"#f8fafc",borderRadius:10,color:"#667085",fontSize:11.5,fontWeight:800}}>{t}</div>}
function fmt(v?:string){if(!v)return"-";const d=new Date(v);return Number.isNaN(d.getTime())?"-":d.toLocaleDateString("tr-TR")}
const card:CSSProperties={background:"#fff",border:"1px solid #e4e7ec",borderRadius:16,padding:16};const row:CSSProperties={display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",border:"1px solid #e4e7ec",borderRadius:11,padding:11,background:"#f8fafc"};const btn:CSSProperties={border:"1px solid #d0d5dd",background:"#fff",borderRadius:8,padding:"7px 9px",fontSize:9.5,fontWeight:900,cursor:"pointer"};const pdf:CSSProperties={...btn,background:"#7f1d1d",borderColor:"#7f1d1d",color:"#fff",textDecoration:"none"};
