"use client";
import {useEffect,useState,type CSSProperties} from "react";
export default function MedulaConnectionPanel(){
 const[connected,setConnected]=useState(false),[simulation,setSimulation]=useState(false),[scenario,setScenario]=useState("SUCCESS"),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[doctorTc,setDoctorTc]=useState(""),[facilityCode,setFacilityCode]=useState("11069903"),[environment,setEnvironment]=useState<"TEST"|"PROD">("TEST"),[patientTc,setPatientTc]=useState(""),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 async function status(){const[rs,rr]=await Promise.all([fetch("/api/admin/medula/simulation",{cache:"no-store",credentials:"include"}),fetch("/api/admin/medula/session",{cache:"no-store",credentials:"include"})]);const s=await rs.json().catch(()=>({})),r=await rr.json().catch(()=>({}));setSimulation(!!s.enabled);setScenario(s.scenario||"SUCCESS");setConnected(!!r.connected)}useEffect(()=>{void status()},[]);
 async function startSimulation(){try{setBusy(true);setMsg("");const r=await fetch("/api/admin/medula/simulation",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({scenario})});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||"Simülasyon açılamadı.");setSimulation(true);setConnected(false);setMsg("MEDULA TEST SİMÜLASYONU aktif. SGK/MEDULA'ya hiçbir dış bağlantı yapılmayacak.")}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function stopSimulation(){await fetch("/api/admin/medula/simulation",{method:"DELETE",credentials:"include"});setSimulation(false);setMsg("Simülasyon kapatıldı. Gerçek işlem için hekim MEDULA oturumu gerekecek.")}
 async function login(){try{setBusy(true);setMsg("");if(simulation)await stopSimulation();const r=await fetch("/api/admin/medula/session",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password,doctorTc:doctorTc||username,facilityCode,environment})});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||"Oturum açılamadı.");setPassword("");setConnected(true);setMsg("Geçici gerçek MEDULA oturumu oluşturuldu.")}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function test(){try{setBusy(true);setMsg("");if(simulation){setMsg(`Simülasyon motoru aktif • Senaryo: ${scenario} • Dış ağ: KAPALI`);return}const r=await fetch("/api/admin/medula/test",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({patientTc})});const j=await r.json();if(!r.ok||!j.success)throw new Error(`${j.resultCode||""} ${j.resultMessage||j.error||"Bağlantı doğrulanamadı."}`.trim());setMsg(`MEDULA bağlantısı doğrulandı. Kod: ${j.resultCode||"0000"}`)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function logout(){await fetch("/api/admin/medula/session",{method:"DELETE",credentials:"include"});setConnected(false);setMsg("MEDULA oturumu kapatıldı.")}
 return <section style={{...card,borderColor:simulation?"#f59e0b":"#e4e7ec"}}><div style={head}><div><div style={eyebrow}>MEDULA / e-REÇETE</div><h3 style={{margin:"4px 0"}}>{simulation?"TEST Simülasyonu":connected?"Gerçek Oturum Aktif":"Bağlantı Merkezi"}</h3><div style={muted}>{simulation?"Şifre gerektirmez; SGK/MEDULA'ya dış ağ çağrısı yapmaz.":"Gerçek kullanımda parola yalnız kısa süreli şifreli HttpOnly oturumda tutulur."}</div></div><span style={{...badge,background:simulation?"#fef3c7":connected?"#dcfce7":"#f2f4f7",color:simulation?"#92400e":connected?"#15803d":"#475467"}}>{simulation?"SİMÜLASYON":connected?"BAĞLI":"BAĞLI DEĞİL"}</span></div>
 {!simulation&&!connected&&<><div style={{marginTop:14,padding:12,borderRadius:12,background:"#fff7ed",border:"1px solid #fed7aa"}}><b style={{fontSize:11}}>Şifre yoksa güvenli test:</b><div style={{...grid,marginTop:8}}><Field l="Test Senaryosu"><select value={scenario} onChange={e=>setScenario(e.target.value)} style={input}><option value="SUCCESS">Başarılı Akış</option><option value="SEND_ERROR">MEDULA İş Kuralı Hatası</option><option value="TIMEOUT">Zaman Aşımı</option><option value="AUTH_ERROR">Yetki/Oturum Hatası</option></select></Field></div><button disabled={busy} onClick={startSimulation} style={simBtn}>TEST SİMÜLASYONUNU BAŞLAT</button></div><div style={grid}><Field l="Ortam"><select value={environment} onChange={e=>setEnvironment(e.target.value as any)} style={input}><option value="TEST">SGK TEST</option><option value="PROD">GERÇEK MEDULA</option></select></Field><Field l="Hekim / MEDULA Kullanıcı Adı"><input value={username} onChange={e=>setUsername(e.target.value.replace(/\D/g,"").slice(0,11))} style={input}/></Field><Field l="Hekim T.C."><input value={doctorTc} onChange={e=>setDoctorTc(e.target.value.replace(/\D/g,"").slice(0,11))} style={input}/></Field><Field l="Tesis Kodu"><input value={facilityCode} onChange={e=>setFacilityCode(e.target.value.replace(/\D/g,"").slice(0,8))} style={input}/></Field><Field l="MEDULA Parolası"><input type="password" autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)} style={input}/></Field></div><button disabled={busy} onClick={login} style={primary}>Gerçek MEDULA Oturumu Aç</button></>}
 {simulation&&<div style={{marginTop:14,padding:14,borderRadius:12,background:"#fffbeb",border:"1px solid #fde68a"}}><b style={{fontSize:12,color:"#92400e"}}>Simülasyon aktif • {scenario}</b><div style={{...muted,marginTop:5}}>Gönder, sorgula, hasta reçeteleri ve silme akışları test edilir. Üretilen e-Reçete numaraları <b>SIM-</b> ile başlar ve gerçek değildir.</div><div style={{display:"flex",gap:8,marginTop:10,flexWrap:"wrap"}}><button disabled={busy} onClick={test} style={simBtn}>Simülasyonu Doğrula</button><button onClick={stopSimulation} style={secondary}>Simülasyonu Kapat</button></div></div>}
 {!simulation&&connected&&<><div style={{...grid,marginTop:12}}><Field l="Bağlantı Testi Hasta/Test T.C."><input value={patientTc} onChange={e=>setPatientTc(e.target.value.replace(/\D/g,"").slice(0,11))} style={input}/></Field></div><div style={{display:"flex",gap:8}}><button disabled={busy} onClick={test} style={primary}>MEDULA'yı Doğrula</button><button onClick={logout} style={secondary}>Oturumu Kapat</button></div></>}
 {msg&&<div style={{marginTop:10,padding:10,borderRadius:9,background:"#f8fafc",fontSize:11,fontWeight:800}}>{msg}</div>}<div style={{...muted,marginTop:10}}>Gerçek doktor şifresini kod, ENV, Supabase, log veya ChatGPT mesajına yazmayın.</div></section>}
function Field({l,children}:{l:string;children:any}){return <label style={{display:"grid",gap:5,fontSize:10.5,fontWeight:850,color:"#344054"}}>{l}{children}</label>}
const card:CSSProperties={background:"#fff",border:"1px solid #e4e7ec",borderRadius:16,padding:16};const head:CSSProperties={display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"};const eyebrow:CSSProperties={fontSize:9.5,fontWeight:950,letterSpacing:.7,color:"#9f1239"};const muted:CSSProperties={fontSize:11,color:"#667085",lineHeight:1.5};const badge:CSSProperties={padding:"6px 9px",borderRadius:999,fontSize:9.5,fontWeight:950};const grid:CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10,margin:"14px 0"};const input:CSSProperties={width:"100%",padding:"9px 10px",border:"1px solid #d0d5dd",borderRadius:9,fontSize:11.5};const primary:CSSProperties={border:0,borderRadius:9,padding:"9px 12px",background:"#7f1d1d",color:"#fff",fontSize:10.5,fontWeight:950,cursor:"pointer"};const secondary:CSSProperties={...primary,background:"#fff",color:"#344054",border:"1px solid #d0d5dd"};const simBtn:CSSProperties={...primary,background:"#b45309"};
