"use client";
import {useCallback,useEffect,useMemo,useState,type CSSProperties} from "react";

type Kind="LABORATORY"|"AUDIOMETRY"|"SFT"|"VACCINATION";
type Props={employee:{id:string;company_id?:string}&Record<string,any>;kind:Kind;title:string;description:string;legacyKeys:string[];fields:Array<{key:string;label:string;type?:"text"|"number";unit?:string;placeholder?:string}>};
type Row={id:string;record_type:Kind;test_date:string;next_due_date?:string|null;provider?:string|null;report_no?:string|null;summary?:string|null;notes?:string|null;result_status?:string|null;details?:Record<string,any>;source?:string};
const resultOptions=[['NOT_EVALUATED','Değerlendirilmedi'],['NORMAL','Normal'],['FOLLOW_UP','Takip'],['ABNORMAL','Anormal']];
function emptyForm(fields:Props['fields']){return{testDate:new Date().toISOString().slice(0,10),nextDueDate:'',provider:'',reportNo:'',resultStatus:'NOT_EVALUATED',summary:'',notes:'',details:Object.fromEntries(fields.map(f=>[f.key,'']))}}
export default function HealthTestRegistry({employee,kind,title,description,legacyKeys,fields}:Props){
 const [rows,setRows]=useState<Row[]>([]),[legacy,setLegacy]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editing,setEditing]=useState<string>(''),[saving,setSaving]=useState(false);const [form,setForm]=useState<any>(()=>emptyForm(fields));
 const qs=useMemo(()=>`employeeId=${encodeURIComponent(employee.id)}${employee.company_id?`&companyId=${encodeURIComponent(employee.company_id)}`:''}&type=${kind}`,[employee.id,employee.company_id,kind]);
 const load=useCallback(async()=>{try{setLoading(true);setError('');const [r1,r2]=await Promise.all([fetch(`/api/admin/health-tests?${qs}`,{cache:'no-store',credentials:'include'}),fetch(`/api/admin/ek2?employeeId=${encodeURIComponent(employee.id)}${employee.company_id?`&companyId=${encodeURIComponent(employee.company_id)}`:''}`,{cache:'no-store',credentials:'include'})]);const j1=await r1.json().catch(()=>({})),j2=await r2.json().catch(()=>({}));if(!r1.ok)throw new Error(j1?.error||'Kalıcı sağlık kayıtları alınamadı.');setRows(j1.records||[]);setLegacy((j2.forms||[]).filter((x:any)=>{const raw=x?.raw_json||{};return legacyKeys.some(k=>raw?.[k]!=null&&raw?.[k]!==''&&!(typeof raw[k]==='object'&&Object.keys(raw[k]).length===0))}));}catch(e:any){setError(e?.message||'Kayıtlar alınamadı.')}finally{setLoading(false)}},[qs,employee.id,employee.company_id,legacyKeys.join('|')]);
 useEffect(()=>{void load()},[load]);
 function setDetail(k:string,v:string){setForm((p:any)=>({...p,details:{...p.details,[k]:v}}))}
 async function save(){try{setSaving(true);const payload={employeeId:employee.id,companyId:employee.company_id,recordType:kind,...form};const res=await fetch(editing?`/api/admin/health-tests/${editing}`:'/api/admin/health-tests',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(payload)});const j=await res.json().catch(()=>({}));if(!res.ok||!j.success)throw new Error(j?.error||'Kayıt kaydedilemedi.');setEditing('');setForm(emptyForm(fields));await load()}catch(e:any){alert(e?.message||'Kayıt kaydedilemedi.')}finally{setSaving(false)}}
 function edit(r:Row){setEditing(r.id);setForm({testDate:r.test_date||'',nextDueDate:r.next_due_date||'',provider:r.provider||'',reportNo:r.report_no||'',resultStatus:r.result_status||'NOT_EVALUATED',summary:r.summary||'',notes:r.notes||'',details:{...Object.fromEntries(fields.map(f=>[f.key,''])),...(r.details||{})}});window.scrollTo({top:0,behavior:'smooth'})}
 async function remove(id:string){if(!confirm('Bu kaydı silmek istediğinize emin misiniz?'))return;const r=await fetch(`/api/admin/health-tests/${id}`,{method:'DELETE',credentials:'include'});const j=await r.json().catch(()=>({}));if(!r.ok||!j.success){alert(j?.error||'Kayıt silinemedi.');return}if(editing===id){setEditing('');setForm(emptyForm(fields))}await load()}
 const counts={total:rows.length,normal:rows.filter(x=>x.result_status==='NORMAL').length,follow:rows.filter(x=>x.result_status==='FOLLOW_UP'||x.result_status==='ABNORMAL').length};
 return <div style={{display:'grid',gap:14}}>
  <section style={card}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><div style={eyebrow}>KALICI SAĞLIK KAYDI</div><h2 style={{margin:'5px 0 4px',fontSize:20}}>{title}</h2><div style={{fontSize:11.5,color:'#667085',maxWidth:850,lineHeight:1.55}}>{description}</div></div><div style={{display:'flex',gap:7}}><Pill text={`${counts.total} kayıt`}/><Pill text={`${counts.normal} normal`} good/><Pill text={`${counts.follow} takip`} warn/></div></div></section>
  <section style={card}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,marginBottom:12}}><b>{editing?'Kaydı Düzenle':'Yeni Kayıt'}</b>{editing&&<button onClick={()=>{setEditing('');setForm(emptyForm(fields))}} style={btn}>İptal</button>}</div><div style={grid}>
   <Field label='Test / Uygulama Tarihi'><input type='date' value={form.testDate} onChange={e=>setForm({...form,testDate:e.target.value})} style={input}/></Field><Field label='Sonraki Kontrol'><input type='date' value={form.nextDueDate} onChange={e=>setForm({...form,nextDueDate:e.target.value})} style={input}/></Field><Field label='Kurum / Uygulayan'><input value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})} style={input}/></Field><Field label='Rapor No'><input value={form.reportNo} onChange={e=>setForm({...form,reportNo:e.target.value})} style={input}/></Field><Field label='Sonuç'><select value={form.resultStatus} onChange={e=>setForm({...form,resultStatus:e.target.value})} style={input}>{resultOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>
   {fields.map(f=><Field key={f.key} label={`${f.label}${f.unit?` (${f.unit})`:''}`}><input type={f.type||'text'} value={form.details[f.key]??''} placeholder={f.placeholder||''} onChange={e=>setDetail(f.key,e.target.value)} style={input}/></Field>)}
  </div><Field label='Özet / Sonuç'><textarea value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})} style={{...input,minHeight:70,resize:'vertical'}}/></Field><Field label='Not'><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} style={{...input,minHeight:60,resize:'vertical'}}/></Field><div style={{display:'flex',justifyContent:'flex-end'}}><button disabled={saving} onClick={save} style={primary}>{saving?'Kaydediliyor...':editing?'Değişiklikleri Kaydet':'Kaydet'}</button></div></section>
  <section style={card}><h3 style={{margin:'0 0 11px'}}>Kayıt Geçmişi</h3>{loading?<Empty text='Yükleniyor...'/>:error?<Empty text={error} bad/>:rows.length===0?<Empty text='Henüz kalıcı kayıt yok.'/>:<div style={{display:'grid',gap:9}}>{rows.map(r=><div key={r.id} style={rowStyle}><div style={{minWidth:0}}><div style={{display:'flex',gap:7,alignItems:'center',flexWrap:'wrap'}}><b>{fmt(r.test_date)}</b><Status v={r.result_status}/>{r.report_no&&<Pill text={`Rapor: ${r.report_no}`}/>}</div><div style={{fontSize:11,color:'#667085',marginTop:5}}>{r.provider||'-'} • {r.summary||'Özet girilmemiş'}</div><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:7}}>{fields.filter(f=>String(r.details?.[f.key]??'').trim()).slice(0,6).map(f=><span key={f.key} style={{fontSize:10.5,color:'#475467'}}><b>{f.label}:</b> {String(r.details?.[f.key])}{f.unit?` ${f.unit}`:''}</span>)}</div></div><div style={{display:'flex',gap:6,flex:'0 0 auto'}}><button onClick={()=>edit(r)} style={btn}>Düzenle</button><button onClick={()=>remove(r.id)} style={{...btn,color:'#b91c1c',borderColor:'#fecaca'}}>Sil</button></div></div>)}</div>}</section>
  {legacy.length>0&&<section style={{...card,background:'#fffbeb',borderColor:'#fde68a'}}><div style={{fontWeight:900,color:'#92400e'}}>Eski EK-2 içinde {legacy.length} {title.toLocaleLowerCase('tr-TR')} verisi bulundu</div><div style={{fontSize:11.5,color:'#92400e',margin:'5px 0 10px',lineHeight:1.55}}>Bunlar geriye dönük uyumluluk amacıyla salt okunur gösterilir. Yeni kayıtlar artık <b>health_test_records</b> tablosuna yazılır.</div>{legacy.map(x=><details key={x.id} style={{marginTop:7}}><summary style={{cursor:'pointer',fontSize:11,fontWeight:850}}>{fmt(x.exam_date||x.created_at)} — EK-2 eski veri</summary><pre style={{whiteSpace:'pre-wrap',fontFamily:'inherit',fontSize:10.5,background:'#fff',padding:10,borderRadius:9,overflow:'auto'}}>{JSON.stringify(pickLegacy(x.raw_json||{},legacyKeys),null,2)}</pre></details>)}</section>}
 </div>
}
function pickLegacy(raw:any,keys:string[]){for(const k of keys)if(raw?.[k]!=null&&raw[k]!=='')return raw[k];return{}}
function Field({label,children}:{label:string;children:any}){return <label style={{display:'grid',gap:5,fontSize:10.5,fontWeight:850,color:'#344054',marginBottom:9}}>{label}{children}</label>}
function Pill({text,good,warn}:{text:string;good?:boolean;warn?:boolean}){return <span style={{padding:'5px 8px',borderRadius:999,fontSize:9.5,fontWeight:950,background:good?'#dcfce7':warn?'#fef3c7':'#f2f4f7',color:good?'#15803d':warn?'#b45309':'#475467',whiteSpace:'nowrap'}}>{text}</span>}
function Status({v}:{v?:string|null}){return <Pill text={v==='NORMAL'?'Normal':v==='ABNORMAL'?'Anormal':v==='FOLLOW_UP'?'Takip':'Değerlendirilmedi'} good={v==='NORMAL'} warn={v==='ABNORMAL'||v==='FOLLOW_UP'}/>}
function Empty({text,bad=false}:{text:string;bad?:boolean}){return <div style={{padding:20,borderRadius:11,background:bad?'#fef2f2':'#f8fafc',color:bad?'#b91c1c':'#667085',fontSize:11.5,textAlign:'center',fontWeight:800}}>{text}</div>}
function fmt(v:any){if(!v)return'-';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('tr-TR')}
const card:CSSProperties={background:'#fff',border:'1px solid #e4e7ec',borderRadius:16,padding:16,boxShadow:'0 7px 20px rgba(16,24,40,.035)'};const eyebrow:CSSProperties={fontSize:9.5,fontWeight:950,letterSpacing:.7,color:'#9f1239'};const grid:CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(185px,1fr))',gap:'0 10px'};const input:CSSProperties={width:'100%',border:'1px solid #d0d5dd',borderRadius:9,padding:'9px 10px',fontSize:11.5,background:'#fff',color:'#101828',outline:'none'};const primary:CSSProperties={border:0,borderRadius:9,padding:'10px 14px',background:'#8b1d25',color:'#fff',fontSize:11,fontWeight:950,cursor:'pointer'};const btn:CSSProperties={border:'1px solid #d0d5dd',borderRadius:8,padding:'7px 9px',background:'#fff',color:'#344054',fontSize:9.5,fontWeight:900,cursor:'pointer'};const rowStyle:CSSProperties={display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:12,border:'1px solid #e4e7ec',borderRadius:12,padding:12,background:'#fff'};
