import { createClient } from "@supabase/supabase-js";
import { cookies } from "next/headers";
import { NextRequest,NextResponse } from "next/server";
function s(v:any){return String(v??"").trim()}
function dateOnly(v:any){const x=s(v);return /^\d{4}-\d{2}-\d{2}$/.test(x)?x:null}
function db(){return createClient(process.env.SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false}})}
async function auth(){const c=await cookies();const auth=c.get("dsec_admin_auth")?.value;const role=s(c.get("dsec_admin_role")?.value||"super_admin");const firm=s(c.get("dsec_company_id")?.value);if(auth!=="ok"&&role)return null;if(!["super_admin","admin","company_admin","demo_user"].includes(role))return null;return{role,firm,scoped:role==="company_admin"||role==="demo_user"}}
async function getRecord(id:string,a:any){let q=db().from("health_test_records").select("*").eq("id",id).eq("is_deleted",false);if(a.scoped)q=q.eq("company_id",a.firm);return q.single()}
export async function GET(_:NextRequest,{params}:{params:Promise<{id:string}>}){try{const a=await auth();if(!a)return NextResponse.json({success:false,error:"Yetkisiz erişim."},{status:401});const{id}=await params;const{data,error}=await getRecord(id,a);if(error||!data)return NextResponse.json({success:false,error:"Kayıt bulunamadı."},{status:404});return NextResponse.json({success:true,record:data})}catch(e:any){return NextResponse.json({success:false,error:e?.message||"Kayıt alınamadı."},{status:500})}}
export async function PUT(req:NextRequest,{params}:{params:Promise<{id:string}>}){try{const a=await auth();if(!a)return NextResponse.json({success:false,error:"Yetkisiz erişim."},{status:401});if(a.role==="demo_user")return NextResponse.json({success:false,error:"Demo kullanıcı sağlık testi güncelleyemez."},{status:403});const{id}=await params;const{data:current,error:getErr}=await getRecord(id,a);if(getErr||!current)return NextResponse.json({success:false,error:"Kayıt bulunamadı."},{status:404});const b=await req.json();const patch:any={status:s(b.status||current.status),result_status:s(b.resultStatus??b.result_status??current.result_status)||null,test_date:dateOnly(b.testDate||b.test_date)||current.test_date,next_due_date:dateOnly(b.nextDueDate||b.next_due_date),provider:s(b.provider??current.provider)||null,report_no:s(b.reportNo??b.report_no??current.report_no)||null,summary:s(b.summary??current.summary)||null,notes:s(b.notes??current.notes)||null,details:(b.details&&typeof b.details==="object")?b.details:current.details,examination_id:s(b.examinationId??b.examination_id??current.examination_id)||null,ek2_form_id:s(b.ek2FormId??b.ek2_form_id??current.ek2_form_id)||null};const{data,error}=await db().from("health_test_records").update(patch).eq("id",id).eq("company_id",current.company_id).select("*").single();if(error)throw error;return NextResponse.json({success:true,record:data})}catch(e:any){return NextResponse.json({success:false,error:e?.message||"Kayıt güncellenemedi."},{status:500})}}
export async function DELETE(_:NextRequest,{params}:{params:Promise<{id:string}>}){try{const a=await auth();if(!a)return NextResponse.json({success:false,error:"Yetkisiz erişim."},{status:401});if(a.role==="demo_user")return NextResponse.json({success:false,error:"Demo kullanıcı sağlık testi silemez."},{status:403});const{id}=await params;const{data:current,error:getErr}=await getRecord(id,a);if(getErr||!current)return NextResponse.json({success:false,error:"Kayıt bulunamadı."},{status:404});const{error}=await db().from("health_test_records").update({is_deleted:true,deleted_at:new Date().toISOString()}).eq("id",id).eq("company_id",current.company_id);if(error)throw error;return NextResponse.json({success:true})}catch(e:any){return NextResponse.json({success:false,error:e?.message||"Kayıt silinemedi."},{status:500})}}
